name: "Check for expired student accounts"
on:
  schedule:
    - cron: "0 0 * * *" # KTC Mon, 09:00:00
  workflow_dispatch:
permissions:
  issues: write
  contents: read
jobs:
  check-expired-students:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Nix
        uses: cachix/install-nix-action@v31
      - name: Create issues for expired accounts
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Enter devshell and run the issue creation command
          nix develop -c inv expired-accounts-create-issues
